### ISSUE TITLE
Migrate project setup to poetry

### ISSUE THREAD

**Issue by Nicoretti** [exasol/pyexasol#103]
## Summary
Migrate to poetry based project setup on `Test-Automation` branch.
```[tasklist]
### Tasks
- [x] Add dev dependencies to pyproject.tom
- [x] Remove old build and project artifacts
- [x] Merge into Test-Automation branch
```
