### ISSUE TITLE
📝 Add a `.git-blame-ignore-revs` file

### ISSUE THREAD

**Issue by Nicoretti** [exasol/pyexasol#163]
# Summary
Add a `.git-blame-ignore-revs` file, containing the SHA1 of the merged changes of [PR-161](https://github.com/exasol/pyexasol/pull/161).

# Details
A `.git-blame-ignore-revs` file needs to be added to the repository. This file helps to ignore certain commits when using `git blame`, especially those related to code reformatting, to keep the blame history clean and focused on actual code changes.

For details on ignoring specific revisions, please refer to the [git-blame documentation](https://git-scm.com/docs/git-blame) or read a brief summary in the article about [introducing black to your project - avoid running git blame](https://introducing-black-to-your-project-avoid-running-git-blame).

## Background & Context
While we want to harmonize Exasol’s projects in terms of code formatting, ideally we want to keep git blame intact because it can be a valuable feature for tracking down additional information around specific lines of code, who wrote them, and why (e.g. commit message), etc. Since reformatting the codebase would void this information, this commit shall be ignored by git blame.

See also https://github.com/exasol/pyexasol/pull/161#issuecomment-2523646568.

## Tasks
- [ ] Track down the SHA1 of the squashed commit of [PR-161](https://github.com/exasol/pyexasol/pull/161)
- [ ] Add the `.git-blame-ignore-revs` file
- [ ] Add the tracked down SHA1 to the `.git-blame-ignore-revs` file
